# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-07 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(blank=True, max_length=255, verbose_name='hostname')),
                ('uptime', models.CharField(max_length=255, verbose_name='uptime')),
                ('cpu_stat', models.CharField(max_length=50, verbose_name='cpu_stat')),
                ('date_time', models.DateTimeField()),
            ],
        ),
    ]
